import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { format as dateFnsFormat } from 'date-fns';
import { es, enUS } from 'date-fns/locale';

type Language = 'en' | 'es';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, gender?: 'male' | 'female' | 'other' | null) => string;
  formatDate: (date: Date | number, formatStr: string) => string;
}

const translations: Record<string, Record<Language, string>> = {
  'Parent': { en: 'Parent', es: 'Padre/Madre' },
  'Parent_male': { en: 'Father', es: 'Padre' },
  'Parent_female': { en: 'Mother', es: 'Madre' },
  'Child': { en: 'Child', es: 'Hijo/Hija' },
  'Child_male': { en: 'Son', es: 'Hijo' },
  'Child_female': { en: 'Daughter', es: 'Hija' },
  'Spouse': { en: 'Spouse', es: 'Esposo/a' },
  'Spouse_male': { en: 'Husband', es: 'Esposo' },
  'Spouse_female': { en: 'Wife', es: 'Esposa' },
  'Sibling': { en: 'Sibling', es: 'Hermano/a' },
  'Sibling_male': { en: 'Brother', es: 'Hermano' },
  'Sibling_female': { en: 'Sister', es: 'Hermana' },
  'Step-Parent': { en: 'Step-Parent', es: 'Padrastro/Madrastra' },
  'Step-Parent_male': { en: 'Step-Father', es: 'Padrastro' },
  'Step-Parent_female': { en: 'Step-Mother', es: 'Madrastra' },
  'Step-Child': { en: 'Step-Child', es: 'Hijastro/a' },
  'Step-Child_male': { en: 'Step-Son', es: 'Hijastro' },
  'Step-Child_female': { en: 'Step-Daughter', es: 'Hijastra' },
  'Step-Sibling': { en: 'Step-Sibling', es: 'Hermanastro/a' },
  'Step-Sibling_male': { en: 'Step-Brother', es: 'Hermanastro' },
  'Step-Sibling_female': { en: 'Step-Sister', es: 'Hermanastra' },
  'Half-Sibling': { en: 'Half-Sibling', es: 'Medio hermano/a' },
  'Half-Sibling_male': { en: 'Half-Brother', es: 'Medio hermano' },
  'Half-Sibling_female': { en: 'Half-Sister', es: 'Media hermana' },
  'Cousin': { en: 'Cousin', es: 'Primo/a' },
  'Cousin_male': { en: 'Cousin (M)', es: 'Primo' },
  'Cousin_female': { en: 'Cousin (F)', es: 'Prima' },
  'Second-Cousin': { en: 'Second Cousin', es: 'Primo/a segundo/a' },
  'Second-Cousin_male': { en: 'Second Cousin (M)', es: 'Primo segundo' },
  'Second-Cousin_female': { en: 'Second Cousin (F)', es: 'Prima segunda' },
  'Cousin-in-law': { en: 'Cousin-in-law', es: 'Primo/a político/a' },
  'Cousin-in-law_male': { en: 'Cousin-in-law (M)', es: 'Primo político' },
  'Cousin-in-law_female': { en: 'Cousin-in-law (F)', es: 'Prima política' },
  'Grandparent': { en: 'Grandparent', es: 'Abuelo/a' },
  'Grandparent_male': { en: 'Grandfather', es: 'Abuelo' },
  'Grandparent_female': { en: 'Grandmother', es: 'Abuela' },
  'Grandchild': { en: 'Grandchild', es: 'Nieto/a' },
  'Grandchild_male': { en: 'Grandson', es: 'Nieto' },
  'Grandchild_female': { en: 'Granddaughter', es: 'Nieta' },
  'Great-Grandparent': { en: 'Great-Grandparent', es: 'Bisabuelo/a' },
  'Great-Grandparent_male': { en: 'Great-Grandfather', es: 'Bisabuelo' },
  'Great-Grandparent_female': { en: 'Great-Grandmother', es: 'Bisabuela' },
  'Great-Grandchild': { en: 'Great-Grandchild', es: 'Bisnieto/a' },
  'Great-Grandchild_male': { en: 'Great-Grandson', es: 'Bisnieto' },
  'Great-Grandchild_female': { en: 'Great-Granddaughter', es: 'Bisnieta' },
  'Great-Great-Grandparent': { en: 'Great-Great-Grandparent', es: 'Tatarabuelo/a' },
  'Great-Great-Grandparent_male': { en: 'Great-Great-Grandfather', es: 'Tatarabuelo' },
  'Great-Great-Grandparent_female': { en: 'Great-Great-Grandmother', es: 'Tatarabuela' },
  'Great-Great-Grandchild': { en: 'Great-Great-Grandchild', es: 'Tataranieto/a' },
  'Great-Great-Grandchild_male': { en: 'Great-Great-Grandson', es: 'Tataranieto' },
  'Great-Great-Grandchild_female': { en: 'Great-Great-Granddaughter', es: 'Tataranieta' },
  'Chosno-Ancestor': { en: 'Great-Great-Great-Grandparent', es: 'Trastatarabuelo/a' }, 
  'Chosno-Ancestor_male': { en: 'Great-Great-Great-Grandfather', es: 'Trastatarabuelo' },
  'Chosno-Ancestor_female': { en: 'Great-Great-Great-Grandmother', es: 'Trastatarabuela' },
  'Chosno': { en: 'Great-Great-Great-Grandchild', es: 'Chosno/a' },
  'Chosno_male': { en: 'Great-Great-Great-Grandson', es: 'Chosno' },
  'Chosno_female': { en: 'Great-Great-Great-Granddaughter', es: 'Chosna' },
  'Aunt/Uncle': { en: 'Aunt/Uncle', es: 'Tío/a' },
  'Aunt/Uncle_male': { en: 'Uncle', es: 'Tío' },
  'Aunt/Uncle_female': { en: 'Aunt', es: 'Tía' },
  'Great-Aunt/Uncle': { en: 'Great-Aunt/Uncle', es: 'Tío/a abuelo/a' },
  'Great-Aunt/Uncle_male': { en: 'Great-Uncle', es: 'Tío abuelo' },
  'Great-Aunt/Uncle_female': { en: 'Great-Aunt', es: 'Tía abuela' },
  'Niece/Nephew': { en: 'Niece/Nephew', es: 'Sobrino/a' },
  'Niece/Nephew_male': { en: 'Nephew', es: 'Sobrino' },
  'Niece/Nephew_female': { en: 'Niece', es: 'Sobrina' },
  'Great-Niece/Nephew': { en: 'Great-Niece/Nephew', es: 'Sobrino/a nieto/a' },
  'Great-Niece/Nephew_male': { en: 'Great-Nephew', es: 'Sobrino nieto' },
  'Great-Niece/Nephew_female': { en: 'Great-Niece', es: 'Sobrina nieta' },
  'First-Cousin-Once-Removed': { en: 'First Cousin Once Removed (Up)', es: 'Tío/a segundo/a' },
  'First-Cousin-Once-Removed_male': { en: 'First Cousin Once Removed (Up)', es: 'Tío segundo' },
  'First-Cousin-Once-Removed_female': { en: 'First Cousin Once Removed (Up)', es: 'Tía segunda' },
  'First-Cousin-Once-Removed-Down': { en: 'First Cousin Once Removed (Down)', es: 'Sobrino/a segundo/a' },
  'First-Cousin-Once-Removed-Down_male': { en: 'First Cousin Once Removed (Down)', es: 'Sobrino segundo' },
  'First-Cousin-Once-Removed-Down_female': { en: 'First Cousin Once Removed (Down)', es: 'Sobrina segunda' },
  'Deceased': { en: 'Deceased', es: 'Fallecido/a' },
  'Deceased_male': { en: 'Deceased', es: 'Fallecido' },
  'Deceased_female': { en: 'Deceased', es: 'Fallecida' },
  'Sibling-in-law': { en: 'Sibling-in-law', es: 'Cuñado/a' },
  'Sibling-in-law_male': { en: 'Brother-in-law', es: 'Cuñado' },
  'Sibling-in-law_female': { en: 'Sister-in-law', es: 'Cuñada' },
  'Parent-in-law': { en: 'Parent-in-law', es: 'Suegro/a' },
  'Parent-in-law_male': { en: 'Father-in-law', es: 'Suegro' },
  'Parent-in-law_female': { en: 'Mother-in-law', es: 'Suegra' },
  'Grandparent-in-law': { en: 'Grandparent-in-law', es: 'Abuelo/a político/a' },
  'Grandparent-in-law_male': { en: 'Grandfather-in-law', es: 'Abuelo político' },
  'Grandparent-in-law_female': { en: 'Grandmother-in-law', es: 'Abuela política' },
  'Great-grandparent-in-law': { en: 'Great-grandparent-in-law', es: 'Bisabuelo/a político/a' },
  'Great-grandparent-in-law_male': { en: 'Great-grandfather-in-law', es: 'Bisabuelo político' },
  'Great-grandparent-in-law_female': { en: 'Great-grandmother-in-law', es: 'Bisabuela política' },
  'Child-in-law': { en: 'Child-in-law', es: 'Yerno/Nuera' },
  'Child-in-law_male': { en: 'Son-in-law', es: 'Yerno' },
  'Child-in-law_female': { en: 'Daughter-in-law', es: 'Nuera' },
  'Grandchild-in-law': { en: 'Grandchild-in-law', es: 'Nieto/a político/a' },
  'Grandchild-in-law_male': { en: 'Grandson-in-law', es: 'Nieto político' },
  'Grandchild-in-law_female': { en: 'Granddaughter-in-law', es: 'Nieta política' },
  'Great-grandchild-in-law': { en: 'Great-grandchild-in-law', es: 'Bisnieto/a político/a' },
  'Great-grandchild-in-law_male': { en: 'Great-grandson-in-law', es: 'Bisnieto político' },
  'Great-grandchild-in-law_female': { en: 'Great-granddaughter-in-law', es: 'Bisnieta política' },
  'Godparent': { en: 'Godparent', es: 'Padrino/Madrina' },
  'Godparent_male': { en: 'Godfather', es: 'Padrino' },
  'Godparent_female': { en: 'Godmother', es: 'Madrina' },
  'Godchild': { en: 'Godchild', es: 'Ahijado/a' },
  'Godchild_male': { en: 'Godchild (M)', es: 'Ahijado' },
  'Godchild_female': { en: 'Godchild (F)', es: 'Ahijada' },
  'Ex-Spouse': { en: 'Ex-Spouse', es: 'Ex-Esposo/a' },
  'Ex-Spouse_male': { en: 'Ex-Husband', es: 'Ex-Esposo' },
  'Ex-Spouse_female': { en: 'Ex-Wife', es: 'Ex-Esposa' },
  'Separated': { en: 'Separated', es: 'Separado/a' },
  'Estranged': { en: 'Estranged', es: 'Distanciado/a' },
  'Friend': { en: 'Friend', es: 'Amigo/a' },
  'Other': { en: 'Other', es: 'Otro/a' },
  'are_Spouse': { en: 'are spouses', es: 'son esposos' },
  'are_Ex-Spouse': { en: 'were spouses', es: 'fueron esposos' },
  'are_Separated': { en: 'are separated', es: 'están separados' },
  'are_Estranged': { en: 'are estranged', es: 'están distanciados' },
  'are_Sibling': { en: 'are siblings', es: 'son hermanos' },
  'are_Step-Sibling': { en: 'are step-siblings', es: 'son hermanastros' },
  'are_Half-Sibling': { en: 'are half-siblings', es: 'son medios hermanos' },
  'are_Cousin': { en: 'are cousins', es: 'son primos' },
  'are_Friend': { en: 'are friends', es: 'son amigos' },
  'is': { en: 'is', es: 'es' },
  'to': { en: 'to', es: 'de' },
  'Add Relation': { en: 'Add Relation', es: 'Añadir Relación' },
  'Export': { en: 'Export', es: 'Exportar' },
  'Import': { en: 'Import', es: 'Importar' },
  'Relation': { en: 'Relation', es: 'Relación' },
  'Please fill all fields': { en: 'Please fill all fields', es: 'Por favor completa todos los campos' },
  'Cannot create relationship with themselves': { en: 'Cannot create relationship with themselves', es: 'No pueden tener relación consigo mismos' },
  'Relationship added!': { en: 'Relationship added!', es: '¡Relación añadida!' },
  'Are you sure you want to remove this connection?': { en: 'Are you sure you want to remove this connection?', es: '¿Seguro que quieres eliminar esta conexión?' },
  'Delete': { en: 'Delete', es: 'Eliminar' },
  'Cancel': { en: 'Cancel', es: 'Cancelar' },
  'Mark as Deceased': { en: 'Mark as Deceased', es: 'Marcar como fallecido' },
  'Mark as Deceased_male': { en: 'Mark as Deceased', es: 'Marcar como fallecido' },
  'Mark as Deceased_female': { en: 'Mark as Deceased', es: 'Marcar como fallecida' },
  'Mark as Living': { en: 'Mark as Living', es: 'Marcar como vivo' },
  'Mark as Living_male': { en: 'Mark as Living', es: 'Marcar como vivo' },
  'Mark as Living_female': { en: 'Mark as Living', es: 'Marcar como viva' },
  'Marked as deceased': { en: 'Marked as deceased', es: 'Marcado como fallecido/a' },
  'Marked as deceased_male': { en: 'Marked as deceased', es: 'Marcado como fallecido' },
  'Marked as deceased_female': { en: 'Marked as deceased', es: 'Marcada como fallecida' },
  'Marked as living': { en: 'Marked as living', es: 'Marcado como vivo/a' },
  'Marked as living_male': { en: 'Marked as living', es: 'Marcado como vivo' },
  'Marked as living_female': { en: 'Marked as living', es: 'Marcada como viva' },
  'View Photos': { en: 'View Photos', es: 'Ver fotos' },
  'Edit Birthday': { en: 'Edit Data', es: 'Editar datos' },
  'Relationship successfully purged!': { en: 'Relationship successfully purged!', es: '¡Relación eliminada exitosamente!' },
  'Failed to delete relationship.': { en: 'Failed to delete relationship.', es: 'Error al eliminar relación.' },
  'Error contacting server.': { en: 'Error contacting server.', es: 'Error al contactar el servidor.' },
  'Death Date': { en: 'Death Date', es: 'Fecha de fallecimiento' },
  'Marriage Date': { en: 'Marriage Date', es: 'Fecha de casamiento' },
  'Is Deceased': { en: 'Is Deceased', es: '¿Fallecido/a?' },
  'Is Deceased_male': { en: 'Is Deceased', es: '¿Fallecido?' },
  'Is Deceased_female': { en: 'Is Deceased', es: '¿Fallecida?' },
  'Gender': { en: 'Gender', es: 'Género' },
  'Male': { en: 'Male', es: 'Hombre' },
  'Female': { en: 'Female', es: 'Mujer' },
  'Mark as Woman': { en: 'Mark as Woman', es: 'Marcar como mujer' },
  'Mark as Man': { en: 'Mark as Man', es: 'Marcar como hombre' },
  'Set Profile Photo': { en: 'Set as Profile Photo', es: 'Establecer como foto de perfil' },
  'Profile photo updated!': { en: 'Profile photo updated!', es: '¡Foto de perfil actualizada!' },
  'Failed to update profile photo': { en: 'Failed to update profile photo', es: 'Error al actualizar la foto de perfil' },
  'Rename Person': { en: 'Rename Person', es: 'Renombrar persona' },
  'Relationship Tree': { en: 'Relationship Tree', es: 'Árbol Genealógico' },
  'Manage People': { en: 'Manage People', es: 'Gestionar Personas' },
  'Find Assets': { en: 'Find Assets', es: 'Buscar Archivos' },
  'Analytics': { en: 'Analytics', es: 'Analíticas' },
  'Potential Albums': { en: 'Potential Albums', es: 'Álbumes Potenciales' },
  'Missing Locations': { en: 'Missing Locations', es: 'Ubicaciones Faltantes' },
  'Manage Albums': { en: 'Manage Albums', es: 'Gestionar Álbumes' },
  'Import shared': { en: 'Import Shared', es: 'Importar Compartidos' },
  'Geo Heatmap': { en: 'Geo Heatmap', es: 'Mapa de Calor' },
  'Empty Videos': { en: 'Empty Videos', es: 'Videos Vacíos' },
  'Bulk Duplicate Finder': { en: 'Bulk Duplicate Finder', es: 'Buscador de Duplicados' },
  'Search by name': { en: 'Search by name', es: 'Buscar por nombre' },
  'Max Asset Count': { en: 'Max Asset Count', es: 'Máximo fotos' },
  'Person Type': { en: 'Person Type', es: 'Tipo de persona' },
  'All': { en: 'All', es: 'Todos' },
  'Nameless': { en: 'Nameless', es: 'Sin nombre' },
  'Named': { en: 'Named', es: 'Con nombre' },
  'Visibility': { en: 'Visibility', es: 'Visibilidad' },
  'Visible': { en: 'Visible', es: 'Visible' },
  'Hidden': { en: 'Hidden', es: 'Oculto' },
  'Asset Count - ASC': { en: 'Asset Count - ASC', es: 'Nº Fotos - ASC' },
  'Asset Count - DESC': { en: 'Asset Count - DESC', es: 'Nº Fotos - DESC' },
  'Updated At - ASC': { en: 'Updated At - ASC', es: 'Actualizado - ASC' },
  'Updated At - DESC': { en: 'Updated At - DESC', es: 'Actualizado - DESC' },
  'Named Co-occurrences - DESC': { en: 'Named Co-occurrences - DESC', es: 'Coincidencias - DESC' },
  'Named Co-occurrences - ASC': { en: 'Named Co-occurrences - ASC', es: 'Coincidencias - ASC' },
  'Close': { en: 'Close', es: 'Cerrar' },
  'All Families': { en: 'All Families', es: 'Todas las familias' },
  'Show All': { en: 'Show All', es: 'Mostrar todos' },
  'Hide Filtered': { en: 'Hide Filtered', es: 'Ocultar filtrados' },
  'Detailed View': { en: 'Detailed View', es: 'Vista detallada' },
  'Compact View': { en: 'Compact View', es: 'Vista compacta' },
  'Unlock Layout': { en: 'Unlock Layout', es: 'Desbloquear diseño' },
  'Lock Layout': { en: 'Lock Layout', es: 'Bloquear diseño' },
  'Clear': { en: 'Clear', es: 'Limpiar' },
  'Detailed': { en: 'Detailed', es: 'Detallado' },
  'Compact': { en: 'Compact', es: 'Compacto' },
  'Menu': { en: 'Menu', es: 'Menú' },
  'Assets': { en: 'Photos', es: 'Fotos' },
  'Merge': { en: 'Merge', es: 'Combinar' },
  'Show': { en: 'Show', es: 'Mostrar' },
  'Hide': { en: 'Hide', es: 'Ocultar' },
  'Share': { en: 'Share', es: 'Compartir' },
  'Unknown': { en: 'Unknown', es: 'Desconocido' },
  'Enter name': { en: 'Enter name', es: 'Escribe un nombre' },
  'Create': { en: 'Create', es: 'Crear' },
  'Merge Person': { en: 'Merge Person', es: 'Combinar Personas' },
  'Are you sure you want to merge this person with the selected person?': { 
    en: 'Are you sure you want to merge this person with the selected person?', 
    es: '¿Seguro que quieres combinar esta persona con la seleccionada?' 
  },
  'Success': { en: 'Success', es: 'Éxito' },
  'Person updated successfully': { en: 'Person updated successfully', es: 'Persona actualizada correctamente' },
  'Error': { en: 'Error', es: 'Error' },
  'Failed to update person': { en: 'Failed to update person', es: 'Error al actualizar persona' },
  'Confirm': { en: 'Confirm', es: 'Confirmar' },
  'Toggle navigation menu': { en: 'Toggle navigation menu', es: 'Alternar menú de navegación' },
  'Failed to fetch similar people': { en: 'Failed to fetch similar people', es: 'Error al buscar personas similares' },
  'People merged successfully': { en: 'People merged successfully', es: 'Personas combinadas con éxito' },
  'Failed to merge people': { en: 'Failed to merge people', es: 'Error al combinar personas' },
  'Search Results': { en: 'Search Results', es: 'Resultados de búsqueda' },
  'Similar People': { en: 'Similar People', es: 'Personas similares' },
  'No Results Found': { en: 'No Results Found', es: 'No se encontraron resultados' },
  'No Similar People Found': { en: 'No Similar People Found', es: 'No se encontraron personas similares' },
  'Please search for the person': { en: 'Please search for the person', es: 'Por favor busca a la persona' },
  'Please search for people': { en: 'Please search for people', es: 'Por favor busca personas' },
  'Untagged Person': { en: 'Untagged Person', es: 'Persona sin etiqueta' },
  'Search and select people to merge with': { en: 'Search and select people to merge with', es: 'Busca y selecciona personas para combinar' },
  'Threshold': { en: 'Threshold', es: 'Umbral' },
  'Threshold (0 to 1)': { en: 'Threshold (0 to 1)', es: 'Umbral (0 a 1)' },
  'Name': { en: 'Name', es: 'Nombre' },
  'Select a name': { en: 'Select a name', es: 'Selecciona un nombre' },
  'No Selections Yet': { en: 'No Selections Yet', es: 'Sin selecciones aún' },
  'Select All': { en: 'Select All', es: 'Seleccionar todos' },
  'Search people...': { en: 'Search people...', es: 'Buscar personas...' },
  'Tagged': { en: 'Tagged', es: 'Etiquetado' },
  'People': { en: 'People', es: 'Personas' },
  'Full Name': { en: 'Full Name', es: 'Nombre completo' },
  'Nickname / Alias': { en: 'Nickname / Alias', es: 'Apodo / Alias' },
  'e.g. El Negro, Pepito': { en: 'e.g. Buddy, Junior', es: 'Ejem: El Negro, Pepito' },
  'Day': { en: 'Day', es: 'Día' },
  'Month': { en: 'Month', es: 'Mes' },
  'Year': { en: 'Year', es: 'Año' },
  'Save': { en: 'Save', es: 'Guardar' },
  'Birthday removed': { en: 'Birthday removed', es: 'Fecha eliminada' },
  'Failed to update': { en: 'Failed to update', es: 'Error al actualizar' },
  'Failed to remove': { en: 'Failed to remove', es: 'Error al eliminar' },
  'years old': { en: 'years old', es: 'años' },
  'No date': { en: 'No date', es: 'Sin fecha' },
  'January': { en: 'January', es: 'Enero' },
  'February': { en: 'February', es: 'Febrero' },
  'March': { en: 'March', es: 'Marzo' },
  'April': { en: 'April', es: 'Abril' },
  'May': { en: 'May', es: 'Mayo' },
  'June': { en: 'June', es: 'Junio' },
  'July': { en: 'July', es: 'Julio' },
  'August': { en: 'August', es: 'Agosto' },
  'September': { en: 'September', es: 'Septiembre' },
  'October': { en: 'October', es: 'Octubre' },
  'November': { en: 'November', es: 'Noviembre' },
  'December': { en: 'December', es: 'Diciembre' },
  'Other_male': { en: 'Other', es: 'Otro' },
  'Other_female': { en: 'Other', es: 'Otra' },
  'Toggle Language': { en: 'Toggle Language', es: 'Cambiar idioma' },
  'Language / Idioma': { en: 'Language', es: 'Idioma' },
  'Pick a date': { en: 'Pick a date', es: 'Selecciona una fecha' },
  'Select Birthday': { en: 'Select Birthday', es: 'Fecha de nacimiento' },
  'Year Unknown': { en: 'Year Unknown', es: 'Año desconocido' },
  'Delete date': { en: 'Delete date', es: 'Eliminar fecha' },
  'Share Assets': { en: 'Compartir Fotos', es: 'Compartir Fotos' },
  'Share link description': { 
    en: 'Generate a share link for the selected assets and share it with your friends and family.', 
    es: 'Genera un enlace para compartir las fotos seleccionadas con tus amigos y familiares.' 
  },
  'Share Link': { en: 'Share Link', es: 'Enlace para compartir' },
  'Copied': { en: 'Copied', es: 'Copiado' },
  'Copy': { en: 'Copy', es: 'Copiar' },
  'Generate New Link': { en: 'Generate New Link', es: 'Generar nuevo enlace' },
  'Show People': { en: 'Show People', es: 'Mostrar personas' },
  'Link Expires In': { en: 'Link Expires In', es: 'El enlace expira en' },
  'Select duration': { en: 'Select duration', es: 'Selecciona duración' },
  '1 Hour': { en: '1 Hour', es: '1 Hora' },
  '1 Day (24 Hours)': { en: '1 Day (24 Hours)', es: '1 Día (24 Horas)' },
  '7 Days': { en: '7 Days', es: '7 Días' },
  '30 Days': { en: '30 Days', es: '30 Días' },
  '90 Days': { en: '90 Days', es: '90 Días' },
  'Never Expires': { en: 'Never Expires', es: 'Nunca' },
  'Generate Share Link': { en: 'Generate Share Link', es: 'Generar enlace' },
  'Share instruction': { 
    en: 'Generate a share link for the selected assets (either bunch of albums or bunch of people) and share it with your friends and family.',
    es: 'Genera un enlace para compartir las fotos seleccionadas (ya sea un grupo de álbumes o personas) y compártelo.'
  },
  'Share link help': {
    en: 'This is a stateless link, it will not work if you leave the page. Which means it cannot be expired.',
    es: 'Este es un enlace sin estado, dejará de funcionar si sales de la página. Por lo tanto, no puede expirar.'
  },
  'Show people help': {
    en: 'Show the list of people in the shared photos',
    es: 'Mostrar la lista de personas en las fotos compartidas'
  },
  'Expires help': {
    en: 'Should the link expire after the selected time',
    es: '¿Debería expirar el enlace después del tiempo seleccionado?'
  },
  'Add Relationship for': { en: 'Add Relationship for', es: 'Añadir relación para' },
  'Relationship Type': { en: 'Relationship Type', es: 'Tipo de relación' },
  'Save Relationship': { en: 'Save Relationship', es: 'Guardar relación' },
  'Loading...': { en: 'Loading...', es: 'Cargando...' },
  'Load More': { en: 'Load More', es: 'Cargar más' },
  'No photos found': { en: 'No photos found', es: 'No se encontraron fotos' },
  'Rename': { en: 'Rename', es: 'Renombrar' },
  'Oldest first': { en: 'Oldest first', es: 'Más viejas primero' },
  'Newest first': { en: 'Newest first', es: 'Más nuevas primero' },
  'Sort by filename (A-Z)': { en: 'Sort by filename (A-Z)', es: 'Ordenar por nombre (A-Z)' },
  'Remove from tree': { en: 'Remove from tree', es: 'Quitar del árbol' },
  'Renaming...': { en: 'Renaming...', es: 'Renombrando...' },
  'Loading tree...': { en: 'Loading tree...', es: 'Cargando árbol...' },
  'Failed to fetch relationships': { en: 'Failed to fetch relationships', es: 'Error al obtener relaciones' },
  'Failed to add relationship': { en: 'Failed to add relationship', es: 'Error al añadir relación' },
  'Error adding relationship': { en: 'Error adding relationship', es: 'Error al añadir relación' },
  'Relationships imported successfully!': { en: 'Relationships imported successfully!', es: '¡Relaciones importadas con éxito!' },
  'Failed to import data': { en: 'Failed to import data', es: 'Error al importar datos' },
  'Invalid JSON file': { en: 'Invalid JSON file', es: 'Archivo JSON inválido' },
  'Suggested Relationships': { en: 'Suggested Relationships', es: 'Sugerencias de parentesco' },
  'Dismiss': { en: 'Dismiss', es: 'Descartar' },
  'Accept': { en: 'Accept', es: 'Aceptar' },
  'Suggestion blacklisted': { en: 'Suggestion blacklisted', es: 'Sugerencia descartada' },
  'Failed to block suggestion': { en: 'Failed to block suggestion', es: 'Error al descartar sugerencia' },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'es',
  setLang: () => {},
  t: (key) => key,
  formatDate: (date, formatStr) => dateFnsFormat(date, formatStr, { locale: es }),
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>('es'); // Default to spanish as requested

  useEffect(() => {
    const saved = localStorage.getItem('appLang');
    if (saved === 'en' || saved === 'es') setLang(saved);
  }, []);

  const handleSetLang = (newLang: Language) => {
    setLang(newLang);
    localStorage.setItem('appLang', newLang);
  };

  const t = (key: string, gender?: 'male' | 'female' | 'other' | null) => {
    const g = (gender === 'female') ? 'female' : 'male';
    const gKey = `${key}_${g}`;
    if (translations[gKey]) return translations[gKey][lang];
    return translations[key]?.[lang] || key;
  };

  const formatDate = (date: Date | number, formatStr: string) => {
    return dateFnsFormat(date, formatStr, { locale: lang === 'es' ? es : enUS });
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t, formatDate }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
